export const GET_TICKETS_SUCCESS = "GET_TICKETS_SUCCESS"
export const GET_TICKET_SUCCESS = "GET_TICKET_SUCCESS"
export const FILTER_BY_SUBJECT = "FILTER_BY_SUBJECT"
export const NEW_TICKET_STATUS = "NEW_TICKET_STATUS"
